version: '3.8'

services:
    orders-server:
        container_name: order-server
        build:
            context: ./server/
        ports:
            - '5000:5000'
    
    orders-client:
        container_name: orders-client
        build: 
            context: ./client/
        ports:
            - '3000:80'